version: '3'
services:
    backend:
        build: ../../
        volumes:
        - './index.html:/var/www/index.html'
        - './headers.conf:/etc/nginx/location.d/headers.conf'
        ports:
        - '80:80'
