version: '3'
services:
    backend:
        build: ../../
        volumes:
        - './index.php:/var/www/index.php'

    frontend:
        image: abiosoft/caddy
        volumes:
        - './Caddyfile:/etc/Caddyfile'
        ports:
        - '443:443'
